INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'gde-mozhno-nayti-podrobnoe-opisanie-kak-ustanovit-danneo-cms', 'Виталий', 'test@test.ru', 'Где можно найти подробное описание как установить Danneo CMS?', 'На нашем сайте: http://danneo.ru. В разделе Описание / Help  =>  <a href="http://danneo.ru/help/read-installation-danneo-cms.html">Установка</a>', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 1, {time}, {time}, 'kak-voyti-v-admin-panel', 'Александр', 'arisfera@mail.ru', 'Как войти в Админ панель?', 'Для доступа в панель управления вашего сайта, в строке браузера введите: http://ваш_домен/admin/login.php', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'kak-v-shablone-mozhno-vyvesti-na-stranicu-ssylku-na-samu-sebya', 'Николай', '', 'Как в шаблоне можно вывести на страницу ссылку на саму себя?', 'В шаблонах оформления для этого можно использовать системную переменную: {self_url}<br>\r\nСсылка: <a href="{self_url}">Ссылка на эту страницу</a><br>\r\nВ скриптах PHP можно использовать константу: FULL_REQUEST_URI<br>\r\n<xmp>echo ''<a href="''.FULL_REQUEST_URI.''">''.FULL_REQUEST_URI.''</a>'';</xmp>', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'kak-polnostyu-ubrat-blok-registracii-s-sayta', 'Сергей', 'test@test.ru', 'Как полностью убрать блок регистрации с сайта?', 'Отключите данный блок, в панели управления сайтом.\r\nУправление блоками => Блоки => блок "Личный кабинет"', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'gde-izmenit-dopolnitelnoe-uslovie-cookie-administratora', 'Владимир', '', 'Где изменить дополнительное условие cookie администратора?', 'В файле: admin/core/permission.php В самом файле есть комментарии.<br>\r\nНеобходимо изменить значение константы:<br> \r\ndefine("SALT_ADMIN",''123456'');<br>\r\nВместо цифр нужно вписать свое.', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'mozhno-li-udalit-vashi-kopirayty', 'Игорь', 'test@test.ru', 'Можно ли удалить ваши копирайты?', 'Отправьте через онлайн-форму <a href="http://danneo.ru/prices.html">Услуги</a> сообщение администратору сайта.<br>\r\nДля удаления копирайт со страниц вашего сайта, необходимо перевести 600 руб на кошелек:\r\nWebMoney: R410749952972<br>\r\nВ примечании укажите ваш домен, например: <q>Снятие копирайт, для http://ваш_сайт.ru</q><br>\r\nВаш домен будет отмечен, как свободный от копирайт.', 'yes');
INSERT INTO {pref}_{mod} VALUES (NULL, 0, {time}, {time}, 'kak-izmenyat-dobavlyat-udalyat-punkty-menyu', 'Анастасия', '', 'Как изменять добавлять и удалять пункты меню?', 'Данную информацию можно посмотреть на нашем сайте, в разделе <a href="http://danneo.ru/help/read-adjustment-danneo-cms-p4.html">Управление меню</a>', 'yes');

INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'our-development', '', 'Наши разработки', 'Разработки нашей компании', '', '', '', '', 1, '', 'all', '', 'public', 'desc', 1);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'our-clients', '', 'Нашим клиентам', 'Раздел для клиентов', '', '', '', '', 2, '', 'all', '', 'public', 'desc', 0);