TRUNCATE TABLE {pref}_banners;
TRUNCATE TABLE {pref}_banners_zone;
TRUNCATE TABLE {pref}_block;
TRUNCATE TABLE {pref}_block_posit;
TRUNCATE TABLE {pref}_control;
TRUNCATE TABLE {pref}_country;
TRUNCATE TABLE {pref}_country_region;
TRUNCATE TABLE {pref}_mods;
TRUNCATE TABLE {pref}_settings;
TRUNCATE TABLE {pref}_smilie;

INSERT INTO {pref}_banners VALUES (NULL, 'click', 'http://danneo.ru', '', 'Тестовый баннер', 'up/banner/banner.gif', 1000, 100, 90, 'home|news|article|down|photos|media|pages|faq|poll|subscribe|map|user|catalog', 1);
INSERT INTO {pref}_banners_zone VALUES (NULL, 'banner', 'Тестовая');

INSERT INTO {pref}_block_posit VALUES (NULL, 'bigtop', 'Верхние блоки', 1);
INSERT INTO {pref}_block_posit VALUES (NULL, 'top', 'Верхние центр', 2);
INSERT INTO {pref}_block_posit VALUES (NULL, 'left', 'Левые блоки', 3);
INSERT INTO {pref}_block_posit VALUES (NULL, 'right', 'Правые блоки', 4);
INSERT INTO {pref}_block_posit VALUES (NULL, 'bot', 'Нижние центр', 5);
INSERT INTO {pref}_block_posit VALUES (NULL, 'bigbot', 'Нижние блоки', 6);

INSERT INTO {pref}_block VALUES (NULL, 2, 'top', '', 'Поздравляем с установкой!', '<br />\r\n<p><strong>Поздравляем, установка системы полностью завершена!</strong></p>\r\n<p>Danneo CMS, это мультиязычная, мультисайтовая, мультиплатформенная, открытая система управления сайтами.</p>\r\n<p>Простая установка, легкость в управлении, минимальная нагрузка на сервер, а так же широкая базовая комплектация позволяет построить интерактивный веб-сайт любой сложности, и в дальнейшем эффективно им управлять.</p>\r\n<p>Теперь вы можете приступать к добавлению необходимых для работы вашего сайта модулей, блоков, а также созданию уникального, неповторимого контента.</p>\r\n<hr class="lines" />\r\n<p>Danneo CMS - это свободно распространяемая система управления сайтами с открытым исходным кодом.<br />\r\nРазрабатывается в соответствии с лицензией GNU General Public 2.</p>\r\n<p>На все модификации и сборки программ созданных на основе Danneo CMS, а также любые дополнения разрабатываемые для Danneo CMS, распространяется генеральная лицензия GNU GPL.\r\nЭто означает что, они должны быть свободно распространяемые, с открытым исходным кодом.</p>\r\n<p>Если Вы намереваетесь включить Danneo CMS или части кода программы в состав другого свободно используемого программного обеспечения, условия, распространения которого отличаются от условий настоящего Соглашения, Вы должны получить на это разрешение разработчиков Danneo CMS.</p>\r\n<p>Условиями соглашения не разрешается включать Danneo CMS, а также, отдельные функции или части кода принадлежащие Danneo CMS, в состав программ, являющихся чьей-либо собственностью, и выпускаемых под коммерческой лицензией, ограничивающей права на ее свободное распространение.</p> \r\n<p>Устанавливая, копируя или иным образом используя продукт, Вы соглашаетесь с условиями настоящего <a href="http://danneo.ru/license" target="_blank">лицензионного соглашения</a>.</p>\r\n<hr class="lines" />                                           \r\n<p>Сайт разработки: <a href="http://danneo.ru" target="_blank">http://danneo.ru</a><br />\r\nФорум поддержки: <a href="http://forum.danneo.ru" target="_blank">http://forum.danneo.ru</a><br />\r\nОткрытое лицензионное соглашение: <a href="http://danneo.ru/license" target="_blank">http://danneo.ru/license</a></p>\r\n<hr class="lines" /> \r\n<p>Предложения по улучшению функционала, и исправлению ошибок приветствуются.<br />\r\nДобавляйте свои предложения на сайте разработчиков <a href="http://tools.danneo.ru/" target="_blank">DANNEO TOOLS</a>, либо на форуме поддержки <a href="http://forum.danneo.ru" target="_blank">DANNEO FORUM</a>.</p> \r\n<hr class="lines" />                                          \r\n<p>Функционал Danneo CMS проходит тщательную проверку, с учетом совместимости новых технологий, а также возможности расширения в будущем.</p> \r\n<p>Надеемся, что наши разработки окажутся полезными для Вас!</p>', 'yes', 0, 'top', '{"home":{"index":{"index":"yes"}}}', 'all', '', '');

INSERT INTO {pref}_control VALUES (NULL, 'Естественный спутник земли?', 'луна');
INSERT INTO {pref}_control VALUES (NULL, 'Два плюс три будет, прописью?', 'пять');
INSERT INTO {pref}_control VALUES (NULL, 'Сколько дней в году (не високосном), цифрами?', '365');
INSERT INTO {pref}_control VALUES (NULL, 'Десять минус три будет, прописью?', 'семь');
INSERT INTO {pref}_control VALUES (NULL, 'Количество времен года (сезонов), прописью?', 'четыре');

INSERT INTO {pref}_country VALUES (1, 'Азербайджан', 'up/country/AZE.png', 'AZ', 'AZE', 31, 1);
INSERT INTO {pref}_country VALUES (2, 'Армения', 'up/country/ARM.png', 'AR', 'ARM', 51, 2);
INSERT INTO {pref}_country VALUES (3, 'Белоруссия', 'up/country/BLR.png', 'BL', 'BLR', 112, 3);
INSERT INTO {pref}_country VALUES (4, 'Грузия', 'up/country/GEO.png', 'GE', 'GEO', 268, 4);
INSERT INTO {pref}_country VALUES (5, 'Казахстан', 'up/country/KAZ.png', 'KZ', 'KAZ', 398, 5);
INSERT INTO {pref}_country VALUES (6, 'Латвия', 'up/country/LVA.png', 'LV', 'LVA', 428, 6);
INSERT INTO {pref}_country VALUES (7, 'Литва', 'up/country/LTU.png', 'LT', 'LTU', 440, 7);
INSERT INTO {pref}_country VALUES (8, 'Молдавия', 'up/country/MDA.png', 'MD', 'MDA', 4217, 8);
INSERT INTO {pref}_country VALUES (9, 'Россия', 'up/country/RUS.png', 'RU', 'RUS', 643, 9);
INSERT INTO {pref}_country VALUES (10, 'Узбекистан', 'up/country/UZB.png', 'UZ', 'UZB', 860, 10);
INSERT INTO {pref}_country VALUES (11, 'Украина', 'up/country/UKR.png', 'UA', 'UKR', 804, 11);
INSERT INTO {pref}_country VALUES (12, 'Эстония', 'up/country/EST.png', 'EE', 'EST', 233, 12);

INSERT INTO {pref}_country_region VALUES (1, 1, 'Азербайджан', 1);
INSERT INTO {pref}_country_region VALUES (2, 1, 'Нагорный Карабах', 2);
INSERT INTO {pref}_country_region VALUES (3, 1, 'Нахичеванская обл.', 3);
INSERT INTO {pref}_country_region VALUES (4, 2, 'Арагацотн', 1);
INSERT INTO {pref}_country_region VALUES (5, 2, 'Арарат', 2);
INSERT INTO {pref}_country_region VALUES (6, 2, 'Армавир', 3);
INSERT INTO {pref}_country_region VALUES (7, 2, 'Гехаркуник', 5);
INSERT INTO {pref}_country_region VALUES (8, 2, 'Котайк', 6);
INSERT INTO {pref}_country_region VALUES (9, 2, 'Лори', 7);
INSERT INTO {pref}_country_region VALUES (10, 2, 'Вайоц Дзор', 4);
INSERT INTO {pref}_country_region VALUES (11, 2, 'Сюник', 8);
INSERT INTO {pref}_country_region VALUES (12, 2, 'Тавуш', 9);
INSERT INTO {pref}_country_region VALUES (13, 2, 'Ширак', 10);
INSERT INTO {pref}_country_region VALUES (14, 3, 'Брестская обл.', 1);
INSERT INTO {pref}_country_region VALUES (15, 3, 'Витебская обл.', 2);
INSERT INTO {pref}_country_region VALUES (16, 3, 'Гомельская обл.', 3);
INSERT INTO {pref}_country_region VALUES (17, 3, 'Гродненская обл.', 4);
INSERT INTO {pref}_country_region VALUES (18, 3, 'Минская обл.', 5);
INSERT INTO {pref}_country_region VALUES (19, 3, 'Могилевская обл.', 6);
INSERT INTO {pref}_country_region VALUES (20, 4, 'Аджария', 1);
INSERT INTO {pref}_country_region VALUES (21, 4, 'Грузия', 2);
INSERT INTO {pref}_country_region VALUES (22, 5, 'Акмолинская обл.', 1);
INSERT INTO {pref}_country_region VALUES (23, 5, 'Актюбинская обл.', 2);
INSERT INTO {pref}_country_region VALUES (24, 5, 'Алма-Атинская обл.', 3);
INSERT INTO {pref}_country_region VALUES (25, 5, 'Восточно-Казахстанская обл.', 4);
INSERT INTO {pref}_country_region VALUES (26, 5, 'Гурьевская обл.', 5);
INSERT INTO {pref}_country_region VALUES (27, 5, 'Джезказганская обл.', 6);
INSERT INTO {pref}_country_region VALUES (28, 5, 'Жамбылская обл.', 7);
INSERT INTO {pref}_country_region VALUES (29, 5, 'Западно-Казахстанская обл.', 8);
INSERT INTO {pref}_country_region VALUES (30, 5, 'Карагандинская обл.', 9);
INSERT INTO {pref}_country_region VALUES (31, 5, 'Кзылординская обл.', 10);
INSERT INTO {pref}_country_region VALUES (32, 5, 'Кокчетавская обл.', 11);
INSERT INTO {pref}_country_region VALUES (33, 5, 'Кустанайская обл.', 12);
INSERT INTO {pref}_country_region VALUES (34, 5, 'Мангышлакская обл.', 13);
INSERT INTO {pref}_country_region VALUES (35, 5, 'Павлодарская обл.', 14);
INSERT INTO {pref}_country_region VALUES (36, 5, 'Северо-Казахстанская обл.', 15);
INSERT INTO {pref}_country_region VALUES (37, 5, 'Талды-Курганская обл.', 16);
INSERT INTO {pref}_country_region VALUES (38, 5, 'Тургайская обл.', 17);
INSERT INTO {pref}_country_region VALUES (39, 5, 'Чимкентская обл.', 18);
INSERT INTO {pref}_country_region VALUES (40, 6, 'Видземе', 1);
INSERT INTO {pref}_country_region VALUES (41, 6, 'Земгале', 2);
INSERT INTO {pref}_country_region VALUES (42, 6, 'Курземе', 3);
INSERT INTO {pref}_country_region VALUES (43, 6, 'Латгале', 4);
INSERT INTO {pref}_country_region VALUES (44, 7, 'Алитусский уезд', 1);
INSERT INTO {pref}_country_region VALUES (45, 7, 'Вильнюсский уезд', 2);
INSERT INTO {pref}_country_region VALUES (46, 7, 'Каунасский уезд', 3);
INSERT INTO {pref}_country_region VALUES (47, 7, 'Клайпедский уезд', 4);
INSERT INTO {pref}_country_region VALUES (48, 7, 'Мариямпольский уезд', 5);
INSERT INTO {pref}_country_region VALUES (49, 7, 'Панявежский уезд', 6);
INSERT INTO {pref}_country_region VALUES (50, 7, 'Таурагский уезд', 7);
INSERT INTO {pref}_country_region VALUES (51, 7, 'Тельшяйский уезд', 8);
INSERT INTO {pref}_country_region VALUES (52, 7, 'Утенский уезд', 9);
INSERT INTO {pref}_country_region VALUES (53, 7, 'Шяуляйский уезд', 10);
INSERT INTO {pref}_country_region VALUES (54, 8, 'Бельцкий уезд', 1);
INSERT INTO {pref}_country_region VALUES (55, 8, 'Кагульский уезд', 6);
INSERT INTO {pref}_country_region VALUES (56, 8, 'Кишинёв', 7);
INSERT INTO {pref}_country_region VALUES (57, 8, 'Кишинёвский уезд', 8);
INSERT INTO {pref}_country_region VALUES (58, 8, 'Единецкий уезд', 5);
INSERT INTO {pref}_country_region VALUES (59, 8, 'Гагаузия', 3);
INSERT INTO {pref}_country_region VALUES (60, 8, 'Уезд Лапушна', 11);
INSERT INTO {pref}_country_region VALUES (61, 8, 'Оргеевский уезд', 9);
INSERT INTO {pref}_country_region VALUES (62, 8, 'Сорокский уезд', 10);
INSERT INTO {pref}_country_region VALUES (63, 8, 'Дубоссарский уезд', 4);
INSERT INTO {pref}_country_region VALUES (64, 8, 'Бендерский уезд', 2);
INSERT INTO {pref}_country_region VALUES (65, 8, 'Унгенский уезд', 12);
INSERT INTO {pref}_country_region VALUES (66, 9, 'Агинский Бурятский автономный округ', 1);
INSERT INTO {pref}_country_region VALUES (67, 9, 'Адыгея', 2);
INSERT INTO {pref}_country_region VALUES (68, 9, 'Алтай', 3);
INSERT INTO {pref}_country_region VALUES (69, 9, 'Алтайский край', 4);
INSERT INTO {pref}_country_region VALUES (70, 9, 'Амурская область', 5);
INSERT INTO {pref}_country_region VALUES (71, 9, 'Архангельская область', 6);
INSERT INTO {pref}_country_region VALUES (72, 9, 'Астраханская область', 7);
INSERT INTO {pref}_country_region VALUES (73, 9, 'Башкортостан', 8);
INSERT INTO {pref}_country_region VALUES (74, 9, 'Белгородская область', 9);
INSERT INTO {pref}_country_region VALUES (75, 9, 'Брянская область', 10);
INSERT INTO {pref}_country_region VALUES (76, 9, 'Бурятия', 11);
INSERT INTO {pref}_country_region VALUES (77, 9, 'Владимирская область', 12);
INSERT INTO {pref}_country_region VALUES (78, 9, 'Волгоградская область', 13);
INSERT INTO {pref}_country_region VALUES (79, 9, 'Вологодская область', 14);
INSERT INTO {pref}_country_region VALUES (80, 9, 'Воронежская область', 15);
INSERT INTO {pref}_country_region VALUES (81, 9, 'Дагестан', 16);
INSERT INTO {pref}_country_region VALUES (82, 9, 'Еврейская автономный округ', 17);
INSERT INTO {pref}_country_region VALUES (83, 9, 'Ивановская область', 18);
INSERT INTO {pref}_country_region VALUES (84, 9, 'Ингушетия', 19);
INSERT INTO {pref}_country_region VALUES (85, 9, 'Иркутская область', 20);
INSERT INTO {pref}_country_region VALUES (86, 9, 'Кабардино-Балкария', 21);
INSERT INTO {pref}_country_region VALUES (87, 9, 'Калининградская область', 22);
INSERT INTO {pref}_country_region VALUES (88, 9, 'Калмыкия', 23);
INSERT INTO {pref}_country_region VALUES (89, 9, 'Калужская область', 24);
INSERT INTO {pref}_country_region VALUES (90, 9, 'Камчатский край', 25);
INSERT INTO {pref}_country_region VALUES (91, 9, 'Карачаево-Черкессия', 26);
INSERT INTO {pref}_country_region VALUES (92, 9, 'Карелия', 27);
INSERT INTO {pref}_country_region VALUES (93, 9, 'Кемеровская область', 28);
INSERT INTO {pref}_country_region VALUES (94, 9, 'Кировская область', 29);
INSERT INTO {pref}_country_region VALUES (95, 9, 'Коми', 30);
INSERT INTO {pref}_country_region VALUES (96, 9, 'Костромская область', 31);
INSERT INTO {pref}_country_region VALUES (97, 9, 'Краснодарский край', 32);
INSERT INTO {pref}_country_region VALUES (98, 9, 'Красноярский край', 33);
INSERT INTO {pref}_country_region VALUES (99, 9, 'Курганская область', 34);
INSERT INTO {pref}_country_region VALUES (100, 9, 'Курская область', 35);
INSERT INTO {pref}_country_region VALUES (101, 9, 'Ленинградская область', 36);
INSERT INTO {pref}_country_region VALUES (102, 9, 'Липецкая область', 37);
INSERT INTO {pref}_country_region VALUES (103, 9, 'Магаданская область', 38);
INSERT INTO {pref}_country_region VALUES (104, 9, 'Марий-Эл', 39);
INSERT INTO {pref}_country_region VALUES (105, 9, 'Мордовия', 40);
INSERT INTO {pref}_country_region VALUES (106, 9, 'Московская область', 41);
INSERT INTO {pref}_country_region VALUES (107, 9, 'Мурманская область', 42);
INSERT INTO {pref}_country_region VALUES (108, 9, 'Ненецкий автономный округ', 43);
INSERT INTO {pref}_country_region VALUES (109, 9, 'Нижегородская область', 44);
INSERT INTO {pref}_country_region VALUES (110, 9, 'Новгородская область', 45);
INSERT INTO {pref}_country_region VALUES (111, 9, 'Новосибирская область', 46);
INSERT INTO {pref}_country_region VALUES (112, 9, 'Омская область', 47);
INSERT INTO {pref}_country_region VALUES (113, 9, 'Оренбургская область', 48);
INSERT INTO {pref}_country_region VALUES (114, 9, 'Орловская область', 49);
INSERT INTO {pref}_country_region VALUES (115, 9, 'Пензенская область', 50);
INSERT INTO {pref}_country_region VALUES (116, 9, 'Пермский край', 51);
INSERT INTO {pref}_country_region VALUES (117, 9, 'Приморский край', 52);
INSERT INTO {pref}_country_region VALUES (118, 9, 'Псковская область', 53);
INSERT INTO {pref}_country_region VALUES (119, 9, 'Ростовская область', 54);
INSERT INTO {pref}_country_region VALUES (120, 9, 'Рязанская область', 55);
INSERT INTO {pref}_country_region VALUES (121, 9, 'Самарская область', 56);
INSERT INTO {pref}_country_region VALUES (122, 9, 'Саратовская область', 57);
INSERT INTO {pref}_country_region VALUES (123, 9, 'Саха (Якутия)', 58);
INSERT INTO {pref}_country_region VALUES (124, 9, 'Сахалинская область', 59);
INSERT INTO {pref}_country_region VALUES (125, 9, 'Свердловская область', 60);
INSERT INTO {pref}_country_region VALUES (126, 9, 'Северная Осетия', 61);
INSERT INTO {pref}_country_region VALUES (127, 9, 'Смоленская область', 62);
INSERT INTO {pref}_country_region VALUES (128, 9, 'Ставропольский край', 63);
INSERT INTO {pref}_country_region VALUES (129, 9, 'Тамбовская область', 64);
INSERT INTO {pref}_country_region VALUES (130, 9, 'Татарстан', 65);
INSERT INTO {pref}_country_region VALUES (131, 9, 'Тверская область', 66);
INSERT INTO {pref}_country_region VALUES (132, 9, 'Томская область', 67);
INSERT INTO {pref}_country_region VALUES (133, 9, 'Тульская область', 68);
INSERT INTO {pref}_country_region VALUES (134, 9, 'Тыва (Тува)', 69);
INSERT INTO {pref}_country_region VALUES (135, 9, 'Тюменская область', 70);
INSERT INTO {pref}_country_region VALUES (136, 9, 'Удмуртия', 71);
INSERT INTO {pref}_country_region VALUES (137, 9, 'Ульяновская область', 72);
INSERT INTO {pref}_country_region VALUES (138, 9, 'Усть-Ордынский Бурятский автономный округ', 73);
INSERT INTO {pref}_country_region VALUES (139, 9, 'Хабаровский край', 74);
INSERT INTO {pref}_country_region VALUES (140, 9, 'Хакасия', 75);
INSERT INTO {pref}_country_region VALUES (141, 9, 'Ханты-Мансийский автономный округ', 76);
INSERT INTO {pref}_country_region VALUES (142, 9, 'Челябинская область', 77);
INSERT INTO {pref}_country_region VALUES (143, 9, 'Чечня', 78);
INSERT INTO {pref}_country_region VALUES (144, 9, 'Читинская область', 79);
INSERT INTO {pref}_country_region VALUES (145, 9, 'Чувашия', 80);
INSERT INTO {pref}_country_region VALUES (146, 9, 'Чукотский автономный округ', 81);
INSERT INTO {pref}_country_region VALUES (147, 9, 'Ямало-Ненецкий автономный округ', 82);
INSERT INTO {pref}_country_region VALUES (148, 9, 'Ярославская область', 83);
INSERT INTO {pref}_country_region VALUES (149, 10, 'Андижанская обл.', 1);
INSERT INTO {pref}_country_region VALUES (150, 10, 'Бухарская обл.', 2);
INSERT INTO {pref}_country_region VALUES (151, 10, 'Джизакская обл.', 3);
INSERT INTO {pref}_country_region VALUES (152, 10, 'Каракалпакия', 4);
INSERT INTO {pref}_country_region VALUES (153, 10, 'Кашкадарьинская обл.', 5);
INSERT INTO {pref}_country_region VALUES (154, 10, 'Навоийская обл.', 6);
INSERT INTO {pref}_country_region VALUES (155, 10, 'Наманганская обл.', 7);
INSERT INTO {pref}_country_region VALUES (156, 10, 'Самаркандская обл.', 8);
INSERT INTO {pref}_country_region VALUES (157, 10, 'Сурхандарьинская обл.', 9);
INSERT INTO {pref}_country_region VALUES (158, 10, 'Сырдарьинская обл.', 10);
INSERT INTO {pref}_country_region VALUES (159, 10, 'Ташкентская обл.', 11);
INSERT INTO {pref}_country_region VALUES (160, 10, 'Ферганская обл.', 12);
INSERT INTO {pref}_country_region VALUES (161, 10, 'Хорезмская обл.', 13);
INSERT INTO {pref}_country_region VALUES (162, 11, 'Винницкая обл.', 1);
INSERT INTO {pref}_country_region VALUES (163, 11, 'Волынская обл.', 2);
INSERT INTO {pref}_country_region VALUES (164, 11, 'Днепропетровская обл.', 3);
INSERT INTO {pref}_country_region VALUES (165, 11, 'Донецкая обл.', 4);
INSERT INTO {pref}_country_region VALUES (166, 11, 'Житомирская обл.', 5);
INSERT INTO {pref}_country_region VALUES (167, 11, 'Закарпатская обл.', 6);
INSERT INTO {pref}_country_region VALUES (168, 11, 'Запорожская обл.', 7);
INSERT INTO {pref}_country_region VALUES (169, 11, 'Ивано-Франковская обл.', 8);
INSERT INTO {pref}_country_region VALUES (170, 11, 'Киевская обл.', 9);
INSERT INTO {pref}_country_region VALUES (171, 11, 'Кировоградская обл.', 10);
INSERT INTO {pref}_country_region VALUES (172, 11, 'Крымская обл.', 11);
INSERT INTO {pref}_country_region VALUES (173, 11, 'Луганская обл.', 12);
INSERT INTO {pref}_country_region VALUES (174, 11, 'Львовская обл.', 13);
INSERT INTO {pref}_country_region VALUES (175, 11, 'Николаевская обл.', 14);
INSERT INTO {pref}_country_region VALUES (176, 11, 'Одесская обл.', 15);
INSERT INTO {pref}_country_region VALUES (177, 11, 'Полтавская обл.', 16);
INSERT INTO {pref}_country_region VALUES (178, 11, 'Ровенская обл.', 17);
INSERT INTO {pref}_country_region VALUES (179, 11, 'Сумская обл.', 18);
INSERT INTO {pref}_country_region VALUES (180, 11, 'Тернопольская обл.', 19);
INSERT INTO {pref}_country_region VALUES (181, 11, 'Харьковская обл.', 20);
INSERT INTO {pref}_country_region VALUES (182, 11, 'Херсонская обл.', 21);
INSERT INTO {pref}_country_region VALUES (183, 11, 'Хмельницкая обл.', 22);
INSERT INTO {pref}_country_region VALUES (184, 11, 'Черкасская обл.', 23);
INSERT INTO {pref}_country_region VALUES (185, 11, 'Черниговская обл.', 24);
INSERT INTO {pref}_country_region VALUES (186, 11, 'Черновицкая обл.', 25);
INSERT INTO {pref}_country_region VALUES (187, 12, 'Валгамаа', 1);
INSERT INTO {pref}_country_region VALUES (188, 12, 'Вильяндимаа', 2);
INSERT INTO {pref}_country_region VALUES (189, 12, 'Вырумаа', 3);
INSERT INTO {pref}_country_region VALUES (190, 12, 'Ида-Вирумаа', 4);
INSERT INTO {pref}_country_region VALUES (191, 12, 'Йыгевамаа', 5);
INSERT INTO {pref}_country_region VALUES (192, 12, 'Ляэне-Вирумаа', 6);
INSERT INTO {pref}_country_region VALUES (193, 12, 'Ляэнемаа', 7);
INSERT INTO {pref}_country_region VALUES (194, 12, 'Пылвамаа', 8);
INSERT INTO {pref}_country_region VALUES (195, 12, 'Пярнумаа', 9);
INSERT INTO {pref}_country_region VALUES (196, 12, 'Рапламаа', 10);
INSERT INTO {pref}_country_region VALUES (197, 12, 'Сааремаа', 11);
INSERT INTO {pref}_country_region VALUES (198, 12, 'Тартумаа', 12);
INSERT INTO {pref}_country_region VALUES (199, 12, 'Харьюмаа', 13);
INSERT INTO {pref}_country_region VALUES (200, 12, 'Хийумаа', 14);
INSERT INTO {pref}_country_region VALUES (201, 12, 'Ярвамаа', 15);

INSERT INTO {pref}_mods VALUES (NULL, 'home', 'Главная', '', '', '', '', 'Lite', 0, '{"index":{"index":1}}', 'yes', 'no', 0, 'no', 'no', 0);

INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site', 'Danneo CMS', 1, 'site_name', 'echo "<input type=\\"text\\" name=\\"set[site]\\" id=\\"set[site]\\" size=\\"50\\" value=\\"".$conf[''site'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''all_not_empty'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_url', 'http://danneo.ru', 1, 'site_url', 'echo "<input type=\\"url\\" name=\\"set[site_url]\\" size=\\"50\\" value=\\"".$conf[''site_url'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''home_url'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_mail', 'info@site.ru', 1, 'site_mail', 'echo "<input type=\\"email\\" name=\\"set[site_mail]\\" size=\\"50\\" value=\\"".$conf[''site_mail'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''all_not_empty'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_keyword', 'danneo, cms', 0, 'key_words', '$tm->textarea(''set[site_keyword]'',5,50,$conf[''site_keyword''],1);\r\n$tm->outhint($lang[''site_keywords'']);', '$set["site_keyword"] = $set["site_keyword"];');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_descript', 'Система управления сайтами', 0, 'descript', '$tm->textarea(''set[site_descript]'', 5, 50, $conf[''site_descript''], 1);', '$set["site_descript"] = $set["site_descript"];');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_temp', 'Lite', 0, 'site_temp', '$skindir = opendir(WORKDIR.''/template/'');\r\n$sel = $listing = array();\r\nwhile ($name = readdir($skindir)) {\r\n    if ($name != ''.'' && $name != ''..'' && is_dir(WORKDIR.''/template/''.$name)) {\r\n        $listing[] = $name;\r\n    }\r\n}\r\nclosedir($skindir);\r\necho "<select name=\\"set[site_temp]\\" style=\\"width: 210px; margin-right: 7px;\\">";\r\nsort($listing);\r\nfor ($i=0; $i < sizeof($listing); $i++) {\r\n    if ($listing[$i]) {\r\n        echo "<option value=\\"$listing[$i]\\"".(($listing[$i] == $conf[''site_temp'']) ? " selected" : "").">$listing[$i]</option>\\n";\r\n    }\r\n}\r\necho "</select> ";\r\necho " <input name=\\"set[all_temp]\\" value=\\"yes\\" type=\\"checkbox\\" checked>";\r\n$tm->outhint($lang[''temp_global'']);', '$db->query("UPDATE ".$basepref."_mods SET active = ''yes'' WHERE file = ''".$db->escape(preparse_sp($set[''site_home'']))."''");\r\nif (isset($set[''all_temp'']) && $set[''all_temp''] == ''yes'') {\r\n    $db->query("UPDATE ".$basepref."_mods SET temp = ''".$db->escape(preparse_sp($set[''site_temp'']))."''");\r\n}');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_home', 'home', 0, 'site_home', 'echo "<select name=\\"set[site_home]\\" class=\\"sw210\\">";\r\n$inq = $db->query("SELECT * FROM ".$basepref."_mods WHERE active = ''yes'' AND file != ''pages''");\r\nwhile($item = $db->fetchrow($inq)){\r\necho "<option value=\\"$item[file]\\"".(($item[''file''] == $conf[''site_home'']) ? " selected" : "").">$item[name]</option>\\n";\r\n}\r\necho "</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'site_copy', 'DANNEO CMS', 0, 'site_copy', '$tm->textarea(''set[site_copy]'', 5, 50, $conf[''site_copy''], 0, '''', 1, true, ''options'');', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'closed', 'no', 0, 'site_closed', 'echo "<select name=\\"set[closed]\\" class=\\"sw210\\">".\r\n"<option value=\\"yes\\"".(($conf[''closed'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''closed'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["closed"] = ($set["closed"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'closedtext', '<h3>Сайт закрыт на реконструкцию</h3>Как только она будет закончена, мы продолжим свою работу.<br />Приносим извинения, за причинённые неудобства!<br />С уважением, администрация сайта.', 0, 'site_closedtext', '$tm->textarea(''set[closedtext]'', 5, 50, $conf[''closedtext''], 1);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'options', 'lastup', '{time}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'ajax', 'yes', 0, 'ajax', 'echo "<select name=\\"set[ajax]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''ajax'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''ajax'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["ajax"] = ($set["ajax"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'cpu', 'yes', 0, 'cpu', 'echo "<select name=\\"set[cpu]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''cpu'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''cpu'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["cpu"] = ($set["cpu"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'suffix', 'no', 0, 'suffix', 'echo "<select name=\\"set[suffix]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''suffix'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''suffix'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["suffix"] = ($set["suffix"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'gzip', 'no', 0, 'gzip', 'echo "<select name=\\"set[gzip]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''gzip'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''gzip'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["gzip"] = ($set["gzip"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'gziplevel', '0', 0, 'gzip_level', 'echo "<select name=\\"set[gziplevel]\\" class=\\"sw165\\">";\r\n  for($i=1;$i<10;$i++) {\r\n   echo "<option value=\\"".$i."\\"".(($conf[''gziplevel'']==$i) ? '' selected'' : '''').">".$i."</option>";\r\n  }\r\necho "</select>";', '$set["gziplevel"] = preparse($set["gziplevel"],THIS_INT);\r\nif($set["gzip"]==''yes''){\r\n$set["gziplevel"] = ($set["gziplevel"] < 0 || $set["gziplevel"] > 9) ? 0 : $set["gziplevel"];\r\n} else {\r\n$set["gziplevel"] = 0;\r\n}');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'cache', 'no', 0, 'cache', 'echo "<select name=\\"set[cache]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''cache'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''cache'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["cache"] = ($set["cache"] == "yes") ? "yes" : "no";\r\n$set["cachetime"] = ($set["cache"] == "yes") ? $set["cachetime"]  : 0;');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'cachetime', '0', 1, 'cachetime', 'echo "<input type=\\"text\\" name=\\"set[cachetime]\\" size=\\"25\\" maxlength=\\"5\\" value=\\"".$conf[''cachetime'']."\\" required=\\"required\\"> ";', '$set["cachetime"] = preparse($set["cachetime"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'botsys', 'yes', 0, 'botsys', 'echo "<select name=\\"set[botsys]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''botsys'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''botsys'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";\r\n$tm->outhint($lang[''help_botsys'']);', '$set["botsys"] = ($set["botsys"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'filenames', 'yes', 0, 'new_filenames', 'echo "<select name=\\"set[filenames]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''filenames'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''filenames'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";\r\n$tm->outhint($lang[''help_new_filenames'']);', '$set["filenames"] = ($set["filenames"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'redirtime', '3', 1, 'redirtime', 'echo "<input type=\\"text\\" name=\\"set[redirtime]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''redirtime'']."\\"> ";', '$set["redirtime"] = preparse($set["redirtime"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'number', '10,25,50,75,100', 1, 'amount_on_page', 'echo "<input type=\\"text\\" name=\\"set[number]\\" size=\\"25\\" value=\\"".$conf[''number'']."\\"> ";\r\n$tm->outhint($lang[''separate_comma'']);', '$set["number"] = preparse($set["number"],THIS_NUM_COM);');
INSERT INTO {pref}_settings VALUES (NULL, 'system', 'separate_crumb', '<i>»</i>', 0, 'separate_crumb', 'echo "<input type=\\"text\\" name=\\"set[separate_crumb]\\" size=\\"25\\" value=\\"".$conf[''separate_crumb'']."\\"> ";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'search', 'searchcol', '5', 1, 'searchcol', 'echo "<input type=\\"text\\" name=\\"set[searchcol]\\" size=\\"25\\" maxlength=\\"20\\" value=\\"".$conf[''searchcol'']."\\" required=\\"required\\">";', '$set["searchcol"] = preparse($set["searchcol"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'search', 'searchtime', '100', 1, 'searchtime', 'echo "<input type=\\"text\\" name=\\"set[searchtime]\\" size=\\"25\\" maxlength=\\"20\\" value=\\"".$conf[''searchtime'']."\\" required=\\"required\\">";', '$set["searchtime"] = preparse($set["searchtime"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'search', 'searchflood', '6', 1, 'searchflood', 'echo "<input type=\\"text\\" name=\\"set[searchflood]\\" size=\\"25\\" maxlength=\\"20\\" value=\\"".$conf[''searchflood'']."\\" required=\\"required\\">";', '$set["searchflood"] = preparse($set["searchflood"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'search', 'searchmin', '3', 1, 'searchmin', 'echo "<input type=\\"text\\" name=\\"set[searchmin]\\" size=\\"25\\" maxlength=\\"20\\" value=\\"".$conf[''searchmin'']."\\" required=\\"required\\">";', '$set["searchmin"] = preparse($set["searchmin"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'search', 'searchmax', '50', 1, 'searchmax', 'echo "<input type=\\"text\\" name=\\"set[searchmax]\\" size=\\"25\\" maxlength=\\"20\\" value=\\"".$conf[''searchmax'']."\\" required=\\"required\\">";', '$set["searchmax"] = preparse($set["searchmax"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'wateruse', 'no', 0, 'watermarkuse', 'echo "<select name=\\"set[wateruse]\\" class=\\"sw165\\">\r\n<option value=\\"no\\"".(($conf[''wateruse'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\r\n<option value=\\"img\\"".(($conf[''wateruse'']=="img") ? " selected" : "").">".$lang[''all_image'']."</option>\r\n<option value=\\"txt\\"".(($conf[''wateruse'']=="txt") ? " selected" : "").">".$lang[''all_text'']."</option>\r\n</select>";\r\n$tm->outhint($lang[''photos_gd_hint'']);', 'if ($set[''wateruse''] == "img") {\r\n    $set["wateruse"] = "img";\r\n} elseif ($set[''wateruse''] == "txt") {\r\n    $set["wateruse"] = "txt";\r\n} else {\r\n    $set["wateruse"] = "no";\r\n}');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'waterpatch', 'up/watermark.png', 0, 'all_image', 'echo "<input name=\\"set[waterpatch]\\" id=\\"waterpatch\\" size=\\"40\\" maxlength=\\"255\\" type=\\"text\\" value=\\"".$conf[''waterpatch'']."\\">\\n".\r\n"<input class=\\"side-button\\" onclick=\\"javascript:$.filebrowser(''".$sess[''hash'']."'',''/'',''&field[1]=waterpatch'');\\" value=\\"".$lang[''filebrowser'']."\\" type=\\"button\\">\\n";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'watertext', 'danneo.ru', 0, 'all_text', 'echo "<input name=\\"set[watertext]\\" size=\\"25\\" maxlength=\\"25\\" type=\\"text\\" value=\\"".((!empty($conf[''watertext''])) ? $conf[''watertext''] : parse_url($conf[''site_url''], PHP_URL_HOST))."\\">\\n";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'markquality', '50', 1, 'markquality', 'echo "<input type=\\"text\\" name=\\"set[markquality]\\" value=\\"".$conf[''markquality'']."\\" size=\\"25\\" maxlength=\\"3\\" required=\\"required\\">";', '$set["markquality"] = preparse($set["markquality"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'imgquality', '100', 1, 'imgquality', 'echo "<input type=\\"text\\" name=\\"set[imgquality]\\" value=\\"".$conf[''imgquality'']."\\" size=\\"25\\" maxlength=\\"3\\" required=\\"required\\">";', '$set["imgquality"] = preparse($set["imgquality"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'maxfile', '2097152', 0, 'maximal_size', 'echo "<input name=\\"set[maxfile]\\" size=\\"25\\" maxlength=\\"25\\" type=\\"text\\" value=\\"".((!empty($conf[''maxfile''])) ? $conf[''maxfile''] : parse_url($conf[''site_url''], PHP_URL_HOST))."\\">\\n";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'unique', 'yes', 0, 'unique_file', 'echo "<select name=\\"set[unique]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''unique'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''unique'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["unique"] = ($set["unique"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'injpg', 'yes', 0, 'convert_in_jpg', 'echo "<select name=\\"set[injpg]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''injpg'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''injpg'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["injpg"] = ($set["injpg"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'thumb', 'yes', 0, 'miniature_yes', 'echo "<select name=\\"set[thumb]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''thumb'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''thumb'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["thumb"] = ($set["thumb"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'resize', 'crop', 0, 'process', 'echo "<select name=\\"set[resize]\\">".\r\n"<option value=\\"crop\\"".(($conf[''resize'']=="crop") ? " selected" : "").">".$lang[''crop_resize'']."</option>\\n".\r\n"<option value=\\"symm\\"".(($conf[''resize'']=="symm") ? " selected" : "").">".$lang[''all_resize'']."</option>\\n".\r\n"<option value=\\"scal\\"".(($conf[''resize'']=="scal") ? " selected" : "").">".$lang[''scale_resize'']."</option>\\n".\r\n"</select>";', 'if ($set[''resize''] == "symm") {\r\n    $set["resize"] = "symm";\r\n} elseif ($set[''resize''] == "crop") {\r\n    $set["resize"] = "crop";\r\n} else {\r\n    $set["resize"] = "scal";\r\n}');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'width', '145', 0, 'all_width', 'echo "<select name=\\"set[width]\\" class=\\"sw165\\">";\r\nfor ($w = 70; $w <= 300; $w ++) {\r\n    echo "<option value=\\"".$w."\\"".(($w == $conf["width"]) ? " selected" : "").">".$w." px</option>";\r\n    $w = $w + 4;\r\n}\r\necho "</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'height', '90', 0, 'all_height', 'echo "<select name=\\"set[height]\\" class=\\"sw165\\">";\r\nfor ($w = 70; $w <= 300; $w ++) {\r\n    echo "<option value=\\"".$w."\\"".(($w == $conf["height"]) ? " selected" : "").">".$w." px</option>";\r\n    $w = $w + 4;\r\n}\r\necho "</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'rbig', 'yes', 0, 'image_resize', 'echo "<select name=\\"set[rbig]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''rbig'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''rbig'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["rbig"] = ($set["rbig"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'wbig', '800', 0, 'all_width', 'echo "<select name=\\"set[wbig]\\" class=\\"sw165\\">";\r\nfor ($w = 300; $w <= 1900; $w ++) {\r\n    echo "<option value=\\"".$w."\\"".(($w == $conf["wbig"]) ? " selected" : "").">".$w." px</option>";\r\n    $w = $w + 99;\r\n}\r\necho "</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'hbig', '600', 0, 'all_height', 'echo "<select name=\\"set[hbig]\\" class=\\"sw165\\">";\r\nfor ($w = 240; $w <= 1200; $w ++) {\r\n    echo "<option value=\\"".$w."\\"".(($w == $conf["hbig"]) ? " selected" : "").">".$w." px</option>";\r\n    $w = $w + 59;\r\n}\r\necho "</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'upload', 'user_upload', '{"thumb":"yes","resize":"crop","width":140,"height":130,"rbig":"yes","wbig":"800","hbig":"600","unique":"yes","injpg":"yes","wmark":"no"}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'team', 'version', '1.5.5', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'lang', 'langid', '1', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'lang', 'langcode', 'ru', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'lang', 'langcharset', 'utf-8', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'lang', 'langdateset', '2', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'lang', 'langloginset', '3', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'base', 'lastopt', '{time}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'base', 'lastrep', '{time}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'menu', 'act_menu', 'tag', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'menu', 'cache_menu', 'no', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'menu', 'tag_menu', 'strong', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'timezone', '3', 0, 'timezone', 'echo "<select name=\\"set[timezone]\\">\\n";\r\nfor($i=-12; $i<13; $i++){\r\n $gtm = "(GMT ".(($i>0) ? "+" : "")."$i:00)";\r\n if($i==0){ $gtm = "(GMT)"; }\r\n echo "<option value=\\"$i\\"".(($conf[''timezone'']==$i) ? " selected" : "").">".$gtm."</option>\\n";\r\n}\r\necho "</select>\\n";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'formatdate', 'j F, Y', 1, 'format_date', 'echo "<input type=\\"text\\" name=\\"set[formatdate]\\" size=\\"35\\" maxlength=\\"25\\" value=\\"".$conf[''formatdate'']."\\" required=\\"required\\">";  \r\n$tm->outhint($lang[''format_date_hint'']);\r\necho " <a href=\\"http://www.php.net/manual-lookup.php?function=date\\" target=\\"_blank\\">".$lang[''in_details'']."</a>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'formattime', 'H:i', 1, 'format_time', 'echo "<input type=\\"text\\" name=\\"set[formattime]\\" size=\\"35\\" maxlength=\\"25\\" value=\\"".$conf[''formattime'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''format_time_hint'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'acookname', 'UolCJa3Ri4O1lMzDf6CW', 1, 'adm_name_cookie', 'echo "<input type=\\"text\\" name=\\"set[acookname]\\" size=\\"35\\" maxlength=\\"20\\" value=\\"".$conf[''acookname'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''adm_cookies'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'cookname', 'RYz13lodkF5IznIgoC9a', 1, 'cookie', 'echo "<input type=\\"text\\" name=\\"set[cookname]\\" size=\\"35\\" maxlength=\\"20\\" value=\\"".$conf[''cookname'']."\\" required=\\"required\\">";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'time', 'cookexpire', '86400', 1, 'cookies_expire', 'echo "<input type=\\"text\\" name=\\"set[cookexpire]\\" size=\\"35\\" maxlength=\\"20\\" value=\\"".$conf[''cookexpire'']."\\" required=\\"required\\">";\r\n$tm->outhint($lang[''cookies_hint_expire'']);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'apanel', 'apanelset', '{"1":{"skin":"Lite","icon":"yes"}}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'apanel', 'platforms', '', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'integ', 'userbase', 'danneo', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'integ', 'datainteg', '', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'seo', 'anchor', 'yes', 0, 'seo_link', 'echo "<select name=\\"set[anchor]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''anchor'']=="yes") ? " selected" : "").">".$lang[''included'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''anchor'']=="no") ? " selected" : "").">".$lang[''not_included'']."</option>\\n".\r\n"</select>";', '$set["anchor"] = ($set["anchor"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'seo', 'social_bookmark', 'yes', 0, 'social_bookmark', 'echo "<select name=\\"set[social_bookmark]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''social_bookmark'']=="yes") ? " selected" : "").">".$lang[''included'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''social_bookmark'']=="no") ? " selected" : "").">".$lang[''not_included'']."</option>\\n".\r\n"</select>";', '$set["social_bookmark"] = ($set["social_bookmark"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'seo', 'social', '[{"posit":0,"link":"https://twitter.com/intent/tweet?text={title}&url={link}","icon":"up/social/big/twitter.png","alt":"Twitter","act":"yes"},{"posit":1,"link":"http://www.facebook.com/sharer.php?u={link}&t={title}","icon":"up/social/big/facebook.png","alt":"Facebook","act":"yes"},{"posit":2,"link":"http://vk.com/share.php?url={link}&title={title}","icon":"up/social/big/vk.png","alt":"Вконтакте","act":"yes"},{"posit":3,"link":"http://connect.mail.ru/share?share_url={link}","icon":"up/social/big/mail.png","alt":"Мой Мир","act":"no"},{"posit":5,"link":"http://www.odnoklassniki.ru/dk?st.cmd=addShare&st._surl={link}","icon":"up/social/big/odnoklassniki.png","alt":"Одноклассники","act":"yes"},{"posit":6,"link":"https://plus.google.com/share?url={link}","icon":"up/social/big/googleplus.png","alt":"Google+","act":"yes"}]', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'banner', 'banner', 'no', 0, 'banner', 'echo "<select name=\\"set[banner]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''banner'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''banner'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["banner"] = ($set["banner"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'comauto', 'yes', 1, 'comment_auto', 'echo "<select name=\\"set[comauto]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''comauto'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''comauto'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["comauto"] = ($set["comauto"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'comtime', '6', 1, 'comment_time', 'echo "<input type=\\"text\\" name=\\"set[comtime]\\" size=\\"25\\" maxlength=\\"11\\" value=\\"".$conf[''comtime'']."\\" required=\\"required\\">";', '$set["comtime"] = preparse($set["comtime"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'commin', '15', 1, 'comment_min', 'echo "<input type=\\"text\\" name=\\"set[commin]\\" size=\\"25\\" maxlength=\\"3\\" value=\\"".$conf[''commin'']."\\" required=\\"required\\">";', '$set["commin"] = preparse($set["commin"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'comsize', '1000', 1, 'comment_size', 'echo "<input type=\\"text\\" name=\\"set[comsize]\\" size=\\"25\\" maxlength=\\"12\\" value=\\"".$conf[''comsize'']."\\" required=\\"required\\">";', '$set["comsize"] = preparse($set["comsize"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'comwrap', '50', 1, 'comment_wrap', 'echo "<input type=\\"text\\" name=\\"set[comwrap]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''comwrap'']."\\" required=\\"required\\">";', '$set["comwrap"] = preparse($set["comwrap"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'compage', '3', 1, 'comment_page', 'echo "<input type=\\"text\\" name=\\"set[compage]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''compage'']."\\" required=\\"required\\">";', '$set["compage"] = preparse($set["compage"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'comsort', 'desc', 1, 'all_sorting', 'echo "<select name=\\"set[comsort]\\" class=\\"sw165\\">".\r\n"<option value=\\"desc\\"".(($conf[''comsort''] == "desc") ? " selected" : "").">".$lang[''all_desc'']."</option>\\n".\r\n"<option value=\\"asc\\"".(($conf[''comsort''] == "asc") ? " selected" : "").">".$lang[''all_acs'']."</option>\\n".\r\n"</select>";', '$set["comsort"] = ($set["comsort"] == "desc") ? "desc" : "asc";');
INSERT INTO {pref}_settings VALUES (NULL, 'comment', 'combad', 'fuck, sheets, табак, курить, сигареты', 0, 'comment_bad', '$tm->textarea(''set[combad]'', 3, 50, $conf[''combad''], 1);', '');
INSERT INTO {pref}_settings VALUES (NULL, 'nospam', 'captcha', 'yes', 0, 'menu_captcha', 'echo "<select name=\\"set[captcha]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''captcha'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''captcha'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["captcha"] = ($set["captcha"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'nospam', 'control', 'yes', 0, 'control_word', 'echo "<select name=\\"set[control]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''control'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''control'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["control"] = ($set["control"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'nospam', 'usercaptcha', 'yes', 1, 'nocaptcha', 'echo "<select name=\\"set[usercaptcha]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''usercaptcha'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''usercaptcha'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["usercaptcha"] = ($set["usercaptcha"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'nospam', 'usercontrol', 'yes', 1, 'nocontrol', 'echo "<select name=\\"set[usercontrol]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''usercontrol'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''usercontrol'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["usercontrol"] = ($set["usercontrol"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_format', 'text', 0, 'mail_format', 'echo "<select name=\\"set[mail_format]\\" class=\\"sw165\\">".\r\n"<option value=\\"html\\"".(($conf[''mail_format'']=="html") ? " selected" : "").">HTML</option>\\n".\r\n"<option value=\\"text\\"".(($conf[''mail_format'']=="text") ? " selected" : "").">".$lang[''all_text'']."</option>\\n".\r\n"</select>";', '$set["mail_format"] = ($set["mail_format"] == "html") ? "html" : "text";');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_acting', 'mail', 0, 'mail_acting', 'echo "<select name=\\"set[mail_acting]\\" class=\\"sw165\\">".\r\n"<option value=\\"mail\\"".(($conf[''mail_acting'']=="mail") ? " selected" : "").">".$lang[''mail_mail'']."</option>\\n".\r\n"<option value=\\"smtp\\"".(($conf[''mail_acting'']=="smtp") ? " selected" : "").">".$lang[''mail_smtp'']."</option>\\n".\r\n"</select>";', '$set["mail_acting"] = ($set["mail_acting"] == "mail") ? "mail" : "smtp";');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_attach', 'yes', 0, 'mail_attach', 'echo "<select name=\\"set[mail_attach]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''mail_attach'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''mail_attach'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["mail_attach"] = ($set["mail_attach"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_file_type', 'list', 0, 'mail_file_type', 'echo "<select name=\\"set[mail_file_type]\\" class=\\"sw165\\">".\r\n"<option value=\\"list\\"".(($conf[''mail_file_type'']=="list") ? " selected" : "").">".$lang[''mail_list_type'']."</option>\\n".\r\n"<option value=\\"all\\"".(($conf[''mail_file_type'']=="all") ? " selected" : "").">".$lang[''mail_all_type'']."</option>\\n".\r\n"</select>";', '$set["mail_file_type"] = ($set["mail_file_type"] == "list") ? "list" : "all";');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_file_col', '5', 0, 'mail_file_col', 'echo "<input type=\\"text\\" name=\\"set[mail_file_col]\\" value=\\"".$conf[''mail_file_col'']."\\" size=\\"25\\" maxlength=\\"2\\">";', '$set["mail_file_col"] = preparse($set["mail_file_col"], THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_list_mime', '{"1":{"type":"doc","data":"application/mswords"},"2":{"type":"docx","data":"vnd.openxmlformats-officedocument.wordprocessingml.document"},"3":{"type":"gif","data":"image/gif"},"4":{"type":"jpg","data":"image/jpeg"},"5":{"type":"pdf","data":"application/pdf"},"6":{"type":"png","data":"image/png"},"7":{"type":"ppt","data":"application/vnd.ms-powerpoint"},"8":{"type":"rar","data":"application/rar"},"9":{"type":"rtf","data":"text/rtf"},"10":{"type":"tar","data":"application/x-tar"},"11":{"type":"tgz","data":"application/x-tar"},"12":{"type":"txt","data":"text/plain"},"13":{"type":"xls","data":"application/vnd.ms-excel"},"14":{"type":"xlsx","data":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},"15":{"type":"zip","data":"application/zip"}}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'mail', 'mail_smtp', '{"mail_host":"","mail_user":"","mail_pass":"","mail_port":"25","mail_tout":"10"}', 0, '', '', '');
INSERT INTO {pref}_settings VALUES (NULL, 'debug', 'debug_db', 'no', 0, 'debug_db', 'echo "<select name=\\"set[debug_db]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''debug_db'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''debug_db'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["debug_db"] = ($set["debug_db"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'debug', 'debug_code', 'yes', 0, 'debug_code', 'echo "<select name=\\"set[debug_code]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''debug_code'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''debug_code'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["debug_code"] = ($set["debug_code"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'debug', 'debug_code_loc', 'no', 0, 'debug_code_loc', 'echo "<select name=\\"set[debug_code_loc]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''debug_code_loc'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''debug_code_loc'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["debug_code_loc"] = ($set["debug_code_loc"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'debug', 'debug_code_out', 'save', 0, 'debug_code_out', 'echo "<select name=\\"set[debug_code_out]\\" class=\\"sw165\\">".\r\n"<option value=\\"show\\"".(($conf[''debug_code_out'']=="show") ? " selected" : "").">".$lang[''debug_show'']."</option>\\n".\r\n"<option value=\\"save\\"".(($conf[''debug_code_out'']=="save") ? " selected" : "").">".$lang[''debug_save'']."</option>\\n".\r\n"</select>";', '$set["debug_code_out"] = ($set["debug_code_out"] == "show") ? "show" : "save";');
INSERT INTO {pref}_settings VALUES (NULL, 'debug', 'debug_code_col', '30', 1, 'debug_code_col', 'echo "<input type=\\"text\\" name=\\"set[debug_code_col]\\" value=\\"".$conf[''debug_code_col'']."\\" size=\\"25\\" maxlength=\\"3\\" required=\\"required\\">";', '$set["debug_code_col"] = preparse($set["debug_code_col"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'use_sms', 'yes', 0, 'use_sms', 'echo "<select name=\\"set[use_sms]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''use_sms'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''use_sms'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["use_sms"] = ($set["use_sms"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'service_sms', 'smsc', 0, 'service_sms', 'echo "<select name=\\"set[service_sms]\\" class=\\"sw165\\">".\r\n"<option value=\\"smsru\\"".(($conf[''service_sms'']=="smsru") ? " selected" : "").">SMS.RU</option>\\n".\r\n"<option value=\\"smsc\\"".(($conf[''service_sms'']=="smsc") ? " selected" : "").">".$lang[''sms_center'']."</option>\\n".\r\n"</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsc_login', '', 0, 'adm_login', 'echo "<input type=\\"text\\" name=\\"set[smsc_login]\\" size=\\"25\\" value=\\"".$conf[''smsc_login'']."\\"> ";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsc_password', '', 0, 'adm_passw', 'echo "<input type=\\"text\\" name=\\"set[smsc_password]\\" size=\\"25\\" value=\\"".$conf[''smsc_password'']."\\"> ";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsru_auth', 'smsc', 0, 'Метод аутентификации', 'echo "<select name=\\"set[smsru_auth]\\" class=\\"sw165\\">".\r\n"<option value=\\"login\\"".(($conf[''smsru_auth'']=="login") ? " selected" : "").">".$lang[''adm_login'']." / ".$lang[''adm_passw'']."</option>\\n".\r\n"<option value=\\"api_id\\"".(($conf[''smsru_auth'']=="api_id") ? " selected" : "").">API_ID</option>\\n".\r\n"</select>";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsru_login', '', 0, 'adm_login', 'echo "<input type=\\"text\\" name=\\"set[smsru_login]\\" size=\\"25\\" value=\\"".$conf[''smsru_login'']."\\"> ";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsru_password', '', 0, 'adm_passw', 'echo "<input type=\\"text\\" name=\\"set[smsru_password]\\" size=\\"25\\" value=\\"".$conf[''smsru_password'']."\\"> ";', '');
INSERT INTO {pref}_settings VALUES (NULL, 'sms', 'smsru_api_id', '', 0, 'API_ID', 'echo "<input type=\\"text\\" name=\\"set[smsru_api_id]\\" size=\\"50\\" value=\\"".$conf[''smsru_api_id'']."\\"> ";', '');

INSERT INTO {pref}_site_menu VALUES (NULL, 0, 'dnmtop', 'Верхнее меню', '', '', '', 0, 'dnmtop', '_self', 1);
INSERT INTO {pref}_site_menu VALUES (NULL, 0, 'dnmblock', 'Блочное меню', '', '', '', 0, 'js-block-menu', '_self', 0);
INSERT INTO {pref}_site_menu VALUES (NULL, 0, 'botmenu', 'Нижнее меню', '', '', '', 0, 'bot-menu', '_self', 0);
INSERT INTO {pref}_site_menu VALUES (NULL, 1, '', 'Главная', '', '', '', 0, '', '_self', 0);

INSERT INTO {pref}_smilie VALUES (NULL, ':1:', 'Подмигиваю', 'up/comment/smilie/wink.gif', 1);
INSERT INTO {pref}_smilie VALUES (NULL, ':3:', 'Улыбаюсь', 'up/comment/smilie/smile.gif', 3);
INSERT INTO {pref}_smilie VALUES (NULL, ':4:', 'Грущу', 'up/comment/smilie/frown.gif', 4);
INSERT INTO {pref}_smilie VALUES (NULL, ':5:', 'Доволен', 'up/comment/smilie/rolleyes.gif', 5);
INSERT INTO {pref}_smilie VALUES (NULL, ':6:', 'Злюсь', 'up/comment/smilie/mad.gif', 6);
INSERT INTO {pref}_smilie VALUES (NULL, ':7:', 'Улыбка до ушей', 'up/comment/smilie/biggrin.gif', 7);
INSERT INTO {pref}_smilie VALUES (NULL, ':8:', 'Не понял', 'up/comment/smilie/confused.gif', 8);
INSERT INTO {pref}_smilie VALUES (NULL, ':9:', 'ИМХО', 'up/comment/smilie/cool.gif', 9);
INSERT INTO {pref}_smilie VALUES (NULL, ':11:', 'Ух ты', 'up/comment/smilie/eek.gif', 11);
INSERT INTO {pref}_smilie VALUES (NULL, ':2:', 'Доволен', 'up/comment/smilie/redface.gif', 2);
INSERT INTO {pref}_smilie VALUES (NULL, ':10:', 'Бе-бе-бе', 'up/comment/smilie/tongue.gif', 10);