INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'regtype', 'yes', 0, 'registr', 'echo "<select name=\\"set[regtype]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''regtype'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''regtype'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["regtype"] = ($set["regtype"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'regact', 'no', 0, 'act_registr', 'echo "<select name=\\"set[regact]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''regact'']=="yes") ? " selected" : "").">".$lang[''act_registr_mail'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''regact'']=="no") ? " selected" : "").">".$lang[''act_registr_no'']."</option>\\n".\r\n"</select>";', '$set["regact"] = ($set["regact"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'regmail', 'no', 0, 'adm_mail_registr', 'echo "<select name=\\"set[regmail]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''regmail'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''regmail'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["regmail"] = ($set["regmail"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'groupact', 'yes', 0, 'all_groups', 'echo "<select name=\\"set[groupact]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''groupact'']=="yes") ? " selected" : "").">".$lang[''included'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''groupact'']=="no") ? " selected" : "").">".$lang[''not_included'']."</option>\\n".\r\n"</select>";', '$set["groupact"] = ($set["groupact"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'groupdef', '0', 0, 'group_def', 'if ($conf[''userbase''] == "danneo" && $conf[''{mod}''][''groupact''] == "yes") \r\n{\r\n	$inq = $db->query("SELECT * FROM ".$basepref."_{mod}_group");\r\n	echo "<select name=\\"set[groupdef]\\" class=\\"sw165\\">"; \r\n	echo "<option value=\\"0\\">".$lang[''{mod}'']."</option>\\n";\r\n\r\n	while ($item = $db->fetchrow($inq)) \r\n	{\r\n		echo "<option value=\\"".$item[''gid'']."\\"".(($conf[''{mod}''][''groupdef'']==$item[''gid'']) ? " selected" : "").">".$item[''title'']."</option>\\n";\r\n	}\r\n	echo "</select>";	\r\n} else {\r\n	echo "".$lang[''{mod}'']."<input type=\\"hidden\\" name=\\"set[groupdef]\\" value=\\"0\\">";\r\n}', '$conf[''{mod}''][''groupdef''] = intval($conf[''{mod}''][''groupdef'']);');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'editmail', 'yes', 0, 're_mail', 'echo "<select name=\\"set[editmail]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''editmail'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''editmail'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>"; $tm->outhint($lang[''re_mail_hint'']);', '$set["editmail"] = ($set["editmail"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'editpass', 'yes', 0, 'chang_pass', 'echo "<select name=\\"set[editpass]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''editpass'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''editpass'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>"; $tm->outhint($lang[''re_pass_hint'']);', '$set["editpass"] = ($set["editpass"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'usergeo', 'yes', 0, 'geo', 'echo "<select name=\\"set[usergeo]\\" class=\\"sw165\\">".\r\n"<option value=\\"yes\\"".(($conf[''{mod}''][''usergeo'']=="yes") ? " selected" : "").">".$lang[''all_yes'']."</option>\\n".\r\n"<option value=\\"no\\"".(($conf[''{mod}''][''usergeo'']=="no") ? " selected" : "").">".$lang[''all_no'']."</option>\\n".\r\n"</select>";', '$set["usergeo"] = ($set["usergeo"] == "yes") ? "yes" : "no";');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'minname', '3', 1, 'mini_login_sym', 'echo "<input type=\\"text\\" name=\\"set[minname]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''{mod}''][''minname'']."\\" required=\\"required\\">";', '$set["minname"] = preparse($set["minname"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'maxname', '18', 1, 'maxi_login_sym', 'echo "<input type=\\"text\\" name=\\"set[maxname]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''{mod}''][''maxname'']."\\" required=\\"required\\">";', '$set["maxname"] = preparse($set["maxname"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'minpass', '5', 1, 'mini_pass_sym', 'echo "<input type=\\"text\\" name=\\"set[minpass]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''{mod}''][''minpass'']."\\" required=\\"required\\">";', '$set["minpass"] = preparse($set["minpass"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'maxpass', '10', 1, 'maxi_pass_sym', 'echo "<input type=\\"text\\" name=\\"set[maxpass]\\" size=\\"25\\" maxlength=\\"2\\" value=\\"".$conf[''{mod}''][''maxpass'']."\\" required=\\"required\\">";', '$set["maxpass"] = preparse($set["maxpass"],THIS_INT);');
INSERT INTO {pref}_settings VALUES (NULL, '{mod}', 'badname', 'guest|user|users|гость|пользователь|администратор', 0, 'no_access_login', '$tm->textarea(''set[badname]'',5,50,$conf[''{mod}''][''badname''],1);', '');

