INSERT INTO {pref}_{mod} VALUES (NULL, 1, 1, {time}, 0, 0, 100.0000, 120.0000, '', 1401569700, 1, 1, 0, 'test-product', 'Тестовый товар, демо-витрина', 'Тестовый товар для оценки работы магазина', 'тестовый, товар', 'Тестовый товар', 'Тестовый демо-товар', '<p>Конвесия покупателя подсознательно специфицирует план размещения, отвоевывая рыночный сегмент. Организация службы маркетинга, вопреки мнению П.Друкера, транслирует межличностный метод изучения рынка, признавая определенные рыночные тенденции.</p>', '<p>Рекламное сообщество, в рамках сегодняшних воззрений, нейтрализует продвигаемый комплексный анализ ситуации, опираясь на опыт западных коллег. Практика однозначно показывает, что стратегия предоставления скидок и бонусов транслирует продвигаемый целевой трафик, работая над проектом. Ассортиментная политика предприятия по-прежнему востребована.</p>', '', 'yes', 10.00, 'kg', 30.00, 10.00, 5.00, 'mm', 'up/screenbig.jpg', 'up/screensmall.jpg', 'left', 'Тестовый товар', '', 'yes', 'all', '', 0, '5,6,7', '{"1":{"thumb":"up/screensmall2.jpg","image":"up/screenbig2.jpg","title":"Товар 2"},"2":{"thumb":"up/screensmall1.jpg","image":"up/screenbig1.jpg","title":"Товар 3"},"3":{"thumb":"up/screensmall.jpg","image":"up/screenbig.jpg","title":"Товар 4"}}', '{"1":{"path":"up/power.rar","title":"Файл 1"}}', '{"6":"Другое название","5":"осенью","9":"ни каких","2":"отсутствуют"}', '{"2":"2"}', 0, 0, 'no', 609, 0, 0);

INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'televisions', 'Телевизоры', '', '', 'Телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"2":"2","5":"5","6":"6","9":"9"}', 1);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'computers', 'Компьютеры', '', '', 'Компьютеры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'phones', 'Телефоны', '', '', 'Телефоны', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 0, 'games-software', 'Игры, софт', '', '', 'Игры, софт', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 1, 'LED-TVs', 'LED телевизоры', '', '', 'LED телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 1, 'OLED-TVs', 'OLED телевизоры', '', '', 'OLED телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 1, 'Ultra-HD-TVs', 'Ultra HD телевизоры', '', '', 'Ultra HD телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 1, '3D-TVs', '3D телевизоры', '', '', '3D телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 1, 'Smart-TVs', 'Smart телевизоры', '', '', 'Smart телевизоры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 2, 'laptops', 'Ноутбуки', '', '', 'Ноутбуки', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 2, 'tablets', 'Планшеты', '', '', 'Планшеты', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 2, 'monoblocks', 'Моноблоки', '', '', 'Моноблоки', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 2, 'monitors', 'Мониторы', '', '', 'Мониторы', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 3, 'cell-phones', 'Сотовые телефоны', '', '', 'Сотовые телефоны', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 3, 'smartphones', 'Смартфоны', '', '', 'Смартфоны', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 3, 'apple-iphone', 'Apple iPhone', '', '', 'Apple iPhone', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","2":"2","3":"3","4":"4","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 3, 'home-phones', 'Домашние телефоны', '', '', 'Домашние телефоны', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"9":"9","2":"2","4":"4"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 3, 'phone-accessories', 'Аксессуары для телефонов', '', '', 'Аксессуары для телефонов', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 4, 'gaming-consoles', 'Игровые приставки', '', '', 'Игровые приставки', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","5":"5","6":"6"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 4, 'game-controllers', 'Игровые манипуляторы', '', '', 'Игровые манипуляторы', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"9":"9","4":"4"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 4, 'games', 'Игры', '', '', 'Игры', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 4, 'software', 'Софт', '', '', 'Софт', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"1":"1","9":"9","2":"2","7":"7","8":"8"}', 0);
INSERT INTO {pref}_{mod}_cat VALUES (NULL, 4, 'game-accessories', 'Аксессуары для игр', '', '', 'Аксессуары для игр', '', '', 0, 'up/catalog/cat/icon.png', 'all', '', 'public', 'desc', 'yes', '{"4":"4","9":"9"}', 0);

INSERT INTO {pref}_{mod}_delivery VALUES (NULL, 0.00, 'RUB', 'up/catalog/icon/pickup-icon.gif', 'Самовывоз', 'Самовывоз представляет собой процедуру заказа товаров через сайт компании с последующими получением и оплатой товара в ближайшем к Вам розничном магазине.', '{"country":{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10,"11":11,"12":12},"state":{"3":3,"4":4,"5":5,"6":6,"10":10,"7":7,"8":8,"9":9,"11":11,"12":12,"13":13,"14":14,"15":15,"16":16,"17":17,"18":18,"19":19,"20":20,"21":21,"22":22,"23":23,"24":24,"25":25,"26":26,"27":27,"28":28,"29":29,"30":30,"31":31,"32":32,"33":33,"34":34,"35":35,"36":36,"37":37,"38":38,"39":39,"40":40,"41":41,"42":42,"43":43,"44":44,"45":45,"46":46,"47":47,"48":48,"49":49,"50":50,"51":51,"52":52,"53":53,"54":54,"64":64,"59":59,"63":63,"58":58,"55":55,"56":56,"57":57,"61":61,"62":62,"60":60,"65":65,"66":66,"67":67,"68":68,"69":69,"70":70,"71":71,"72":72,"73":73,"74":74,"75":75,"76":76,"77":77,"78":78,"79":79,"80":80,"81":81,"82":82,"83":83,"84":84,"85":85,"86":86,"87":87,"88":88,"89":89,"90":90,"91":91,"92":92,"93":93,"94":94,"95":95,"96":96,"97":97,"98":98,"99":99,"100":100,"101":101,"102":102,"103":103,"104":104,"105":105,"106":106,"107":107,"108":108,"109":109,"110":110,"111":111,"112":112,"113":113,"114":114,"115":115,"116":116,"117":117,"118":118,"119":119,"120":120,"121":121,"122":122,"123":123,"124":124,"125":125,"126":126,"127":127,"128":128,"129":129,"130":130,"131":131,"132":132,"133":133,"134":134,"135":135,"136":136,"137":137,"138":138,"139":139,"140":140,"141":141,"142":142,"143":143,"144":144,"145":145,"146":146,"147":147,"148":148,"149":149,"150":150,"151":151,"152":152,"153":153,"154":154,"155":155,"156":156,"157":157,"158":158,"159":159,"160":160,"161":161,"162":162,"163":163,"164":164,"165":165,"166":166,"167":167,"168":168,"169":169,"170":170,"171":171,"172":172,"173":173,"174":174,"175":175,"176":176,"177":177,"178":178,"179":179,"180":180,"181":181,"182":182,"183":183,"184":184,"185":185,"186":186,"187":187,"188":188,"189":189,"190":190,"191":191,"192":192,"193":193,"194":194,"195":195,"196":196,"197":197,"198":198,"199":199,"200":200,"201":201},"data":"fix","percent":"0.00"}', 1, 'custom', '', 1);
INSERT INTO {pref}_{mod}_delivery VALUES (NULL, 0.00, '', 'up/catalog/icon/courier-icon.gif', 'Курьером по Москве и Московской области', 'Время доставки согласовывается с менеджером Службы доставки, который обязательно свяжется с Вами сразу после того, как Вы разместите свой заказ.', '{"data":{"1":{"title":"Москва","price":"1000.00","action":"fix","percent":"0.00"}},"country":{"9":9},"state":{"106":"106"}}', 0, 'auto', 'courier', 1);
INSERT INTO {pref}_{mod}_delivery VALUES (NULL, 0.00, '', 'up/catalog/icon/post-icon.gif', 'Почта России', 'Заказ посылается почтовым отправлением Почтой России. В стоимость заказа будет также входить стоимость почтового отправления, упаковки почтового отправления, страховой сбор взимаемый Почтой России с посылок с объявленной ценностью.', '{"avia":"10.00","maxweight":"20.00","pricevalue":"3.00","tarifweight":"10.00","priceone":{"1":"53.45","2":"58.90","3":"77.40","4":"103.55","5":"116.65"},"pricetwo":{"1":"4.40","2":"4.70","3":"5.90","4":"7.55","5":"8.30"},"state":{"119":3,"97":3,"106":3},"country":{"9":"9"}}', 0, 'auto', 'rus.post', 1);

INSERT INTO {pref}_{mod}_maker VALUES (NULL, 'electronic-arts', 'Electronic Arts', 'Electronic Arts (EA) крупнейший мировой издатель и разработчик игр для PC, Xbox, PlayStation, Wii, Mobile, Online, PSP, и Nintendo DS. Electronic Arts Inc. является ведущей международной компанией в сфере интерактивного развлекательного программного обеспечения. EA разрабатывает, публикует и распространяет по всему миру интерактивное программное обеспечение для систем видеоигр и развлечений, персональных компьютеров, беспроводных устройств и Интернета.', '', '', '', 1, 'up/catalog/maker/ea.jpg', 'http://www.ea.com/ru/', '495 580 95 57', 'США, Редвуд, штат Калифорния');
INSERT INTO {pref}_{mod}_maker VALUES (NULL, '1s-softklab', '1С-Софтклаб', 'Российская компания, занимающаяся локализацией и распространением компьютерных игр. Издаёт официальные русские версии игр на PC, PlayStation 2, PlayStation 3, Xbox 360, PS Vita, PlayStation Portable и Wii. Работает совместно с компанией 1C.\r\n\r\nПервая российская компания, которая начала переводить игры не только для PC, но и для игровых приставок.Москва, ул. Селезневская, дом 21', '', '', '', 2, 'up/catalog/maker/softklab.jpg', 'http://games.1c.ru/', '(495) 737-9257', '');
INSERT INTO {pref}_{mod}_maker VALUES (NULL, 'activision', 'Activision', 'Activision, Inc — американская компания по изданию и разработке компьютерных и видеоигр. Была основана 1 октября 1979 года.', '', '', '', 4, 'up/catalog/maker/activision.jpg', 'http://www.activision.com/', '(495) 745-55-11', 'Санта-Моника, США');
INSERT INTO {pref}_{mod}_maker VALUES (NULL, 'konami', 'Konami', 'Konami Corporation — один из ведущих разработчиков и издателей видеоигр, игрушек для детей, платёжных карточек, аниме, торговых, игровых, развлекательных автоматов и других продуктов.', '', '', '', 5, 'up/catalog/maker/konami.jpg', 'http://www.konami.com/', '852-2956-0573', 'Konami Digital Entertainment Limited\r\nRomm Nos. 611B, 612 & 613, 6/F,\r\nTsmi Sha Tsui Centre,\r\n66 Moody Road,\r\nKowloon, Hong Kon');
INSERT INTO {pref}_{mod}_maker VALUES (NULL, '2k-games', '2K Games', '2K Games — мировой разработчик, дистрибьютор и издатель интерактивных игр, развлекательного программного обеспечения.', '', '', '', 3, 'up/catalog/maker/2k.jpg', 'http://www.2kgames.com/', '8 800 700 2222 ', 'Новато, Калифорния, США');

INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Платформа', 'checkbox', 0, 1, 1);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Рекомендуемые системные требования', 'text', 0, 0, 9);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Язык интерфейса', 'select', 1, 1, 3);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Тип издания', 'select', 1, 1, 2);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'В официальной продаже в России', 'text', 0, 0, 7);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Альтернативное название', 'text', 0, 0, 5);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'В официальной продаже', 'text', 0, 0, 6);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Мультиплеер', 'radio', 0, 1, 4);
INSERT INTO {pref}_{mod}_option VALUES (NULL, 'Минимальные системные требования', 'text', 0, 0, 8);

INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 9, 'Обычное', 'not', 0.0000, 0);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'PC', 'not', 0.0000, 1);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 2, 'Английский', 'fix', 100.0000, 2);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'X360', 'fix', 504.6000, 2);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 2, 'Немецкий', 'not', 0.0000, 3);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'NDS', 'fix', 400.0000, 6);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 9, 'Расширеннное', 'fix', 50.0000, 0);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 9, 'Премиум', 'fix', 100.0000, 0);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 3, 'нет', 'fix', 0.0000, 1);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 9, 'Дополнительное', 'not', 0.0000, 0);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 2, 'Французкий', 'not', 0.0000, 4);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 3, 'есть', 'fix', 10.0000, 0);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'Wii', 'fix', 800.0000, 4);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'PSP', 'fix', 600.0000, 5);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 2, 'Испанский', 'not', 0.0000, 5);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 1, 'PS3', 'fix', 1000.0000, 3);
INSERT INTO {pref}_{mod}_option_value VALUES (NULL, 2, 'Русский', 'not', 0.0000, 1);

INSERT INTO {pref}_{mod}_payment VALUES (NULL, 'banktrans', 'Банковский перевод', 'Вы можете оплатить заказ через любой банк, действующий на территории России', 'up/catalog/icon/bank-icon.gif', '{"company":"Моя компания","bank":"ОАО &quot;Промсвязьбанк&quot;","giro":"40702810200020624803","inn":"7717039300","kpp":"997750001","correspondent":"30101810400000000555","bik":"044525555 ","print":"0"}', 1, 0, 1);
INSERT INTO {pref}_{mod}_payment VALUES (NULL, 'webmoney', 'WebMoney', 'WebMoney - это универсальное средство для расчетов в Сети, которым сегодня пользуются миллионы людей по всему миру.', 'up/catalog/icon/webmoney-icon.gif', '{"merchantr":"R472687719226","merchantkey":"234234","testmode":"1"}', 1, 0, 1);
INSERT INTO {pref}_{mod}_payment VALUES (NULL, 'robokassa', 'ROBOKASSA', 'Робокасса позволяет организовать прием платежей через множество известных электронных валют (QIWI, Webmoney, Яндекс.Деньги, Rapida Online, MoneyMail,Деньги@mail.ru, RBK Money, EasyPay, LiqPay, Z-payment, TeleMoney), а так же через терминалы оплаты ЭлексНет или SMS.', 'up/catalog/icon/robokassa-icon.gif', '{"merchantlogin":"Danneo","merchantpassw1":"123456ff","merchantpassw2":"123456gg","testmode":"2","result":"http://danneos.ru/catalog/gateway-3","success":"http://danneos.ru/catalog/order-success","failure":"http://danneos.ru/catalog/order-failure"}', 4, 0, 1);

INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 3, 12);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 1, 1);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 1, 3);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 1, 2);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 2, 7);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 2, 8);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 2, 9);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 2, 10);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 4, 2, 11);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 1, 1);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 1, 2);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 9, 14);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 9, 17);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 9, 16);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 2, 7);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 2, 8);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 2, 3, 12);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 1);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 2);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 3);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 4);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 5);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 1, 6);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 2, 7);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 2, 8);
INSERT INTO {pref}_{mod}_product_option VALUES (NULL, 1, 3, 12);

INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'development', 'Разработка', 'Разработка программного обеспечения, это род деятельности или процесс, направленный на создание и поддержание работоспособности, качества и надежности программного обеспечения, используя технологии, методологию и практики из информатики.', '', '', '', '', 90);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'consulting', 'Консалтинг', 'Консалтинг (консультирование) — деятельность по консультированию руководителей, управленцев по широкому кругу вопросов в сфере финансовой, коммерческой, юридической, технологической, технической, экспертной деятельности', '', '', '', '', 50);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'promotion', 'Продвижение', 'Под продвижением понимается комплекс маркетинговых мероприятий, целями которых являются увеличение доли товара, услуги, компании или бренда, занимаемой ими на рынке', '', '', '', '', 0);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'optimization', 'Оптимизация', 'Поисковая оптимизация (англ. search engine optimization, SEO) — комплекс мер по внутренней и внешней оптимизации, для поднятия позиций сайта в результатах выдачи поисковых систем по определенным запросам пользователей', '', '', '', '', 90);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'company', 'Компания', 'Компания — (company) Корпоративное предприятие, которое является юридическим лицом, в отличие от его участников; компания оперирует как самостоятельная единица, успеха которой добиваются все ее члены', '', '', '', '', 50);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'business', 'Бизнес', 'Бизнес - (англ, business - дело, предпринимательство) - инициативная экономическая деятельность, осуществляемая за счет собственных или заемных средств на свой риск и под свою ответственность, ставящая главными целями получение прибыли и развитие собственного дела', '', '', '', '', 0);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'e-commerce', 'Электронная коммерция', 'Электронная коммерция — это сфера экономики, которая включает в себя все финансовые и торговые транзакции, осуществляемые при помощи компьютерных сетей, и бизнес-процессы, связанные с проведением таких транзакций', '', '', '', '', 0);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'integration-business-apps', 'Интеграция бизнес-приложений', 'Бизнес-интеграция состоит в объединении полученной из приложений и источников данных информации с людьми и процессами', '', '', '', '', 0);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'outsourcing', 'Аутсорсинг', 'Аутсорсинг — передача организацией, на основании договора, определённых видов или функций производственной предпринимательской деятельности другой компании, действующей в нужной области', '', '', '', '', 90);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'workflow', 'Документооборот', 'Документооборот – это движение документов в организации с момента их создания или получения до завершения исполнения или отправки', '', '', '', '', 50);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'staff', 'Персонал', 'Персонал (от лат. persona - личность) - коллектив работников или совокупность лиц, осуществляющих трудовые функции на основе трудового договора или контракта', '', '', '', '', 0);
INSERT INTO {pref}_{mod}_tag VALUES (NULL, 'automatic-control', 'Автоматизация', 'Автоматизация, это одно из направлений научно-технического прогресса, использующее саморегулирующие технические средства', '', '', '', '', 0);